dataset_folder: "your_data_folder"
model_type: "resnet50"
batch_size: 16
num_epochs: 10
lr: 0.0001
pretrained_model_path: null
outputs: "output"
image_size: [448, 448]
gradcam: false
gradcam_num_images: 3
gradcam_random_state: 29
patience: 100 #75
loss_type: focal # ce # ce (cross-entropy) hoặc focal, thêm option này để chọn loss function
target_column: cancer